import type { Metadata } from "next";
import { NavBar } from "@/components/shared/NavBar";
import { ThemeProvider } from "@/provider/theme-provider";
import FooterSection from "@/components/shared/footer";


export const metadata: Metadata = {
    title: "Nexora",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >

            <NavBar></NavBar>
            {children}
            <FooterSection></FooterSection>

        </ThemeProvider>

    );
}
