"use client"
import type { Metadata } from "next";
import { NavBar } from "@/components/shared/NavBar";
import { ThemeProvider } from "@/provider/theme-provider";
import FooterSection from "@/components/shared/footer";
import { toast } from "sonner";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import ChatWidget from "@/components/chat/ChatWidget";

export type Role = "ADMIN" | "TEACHER" | "STUDENT";

interface AuthUser {
    id: string;
    name: string;
    email: string;
    image?: string | null;
    role: Role;
    emailVerified: boolean;
}

// export const metadata: Metadata = {
//     title: "Nexora",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const router = useRouter();

    const [user, setUser] = useState<AuthUser | null>(null);
    const [isLoadingUser, setIsLoadingUser] = useState(true); 

    // ── 1. Fetch current session ─────────────────────────
    const fetchMe = useCallback(async () => {
        try {
            const res = await fetch("/api/auth/me", {
                method: "GET",
                credentials: "include",
            });

            if (!res.ok) {
                
                setUser(null);
                return;
            }

            const json = await res.json();

            if (json.success) {
                const raw = json.data.userData ?? json.data; 
                setUser({
                    id: raw.id,
                    name: raw.name,
                    email: raw.email,
                    image: raw.image ?? null,
                    role: raw.role,           
                    emailVerified: raw.emailVerified ?? false,
                });
            } else {
                setUser(null);
            }
        } catch {
            // Network error — treat as logged out
            setUser(null);
        } finally {
            setIsLoadingUser(false);
        }
    }, []);

    useEffect(() => { fetchMe(); }, [fetchMe]);

    // ── 2. Sign-out handler ──────────────────────────────
    const handleSignOut = async () => {
        try {
            await fetch("/api/auth/logout", { method: "POST", credentials: "include" });
        } catch { /* silent — proceed regardless */ }
        setUser(null);
        router.push("/");
        toast.success("Signed out successfully.");
    };

    // ── 3. Change-password handler ───────────────────────
    const handleChangePassword = () => {
        // Navigate to your change-password page, or open a modal
        router.push("/auth/changePassword");
    };

    // ── 4. Verify-email handler ──────────────────────────
    const handleVerifyEmail = async () => {
        if (!user) return;
        try {
            const res = await fetch("/api/auth/resend-verification-email", {
                method: "POST",
                credentials: "include",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ email: user.email }),
            });
            const json = await res.json();
            if (!res.ok || !json.success) throw new Error(json.message ?? "Failed to send");


            toast.success("Verification email sent! Check your inbox.");
            window.location.href = "/auth/verifyEmail"
        } catch (e: any) {
            toast.error(e.message ?? "Could not send verification email.");
            throw e; // re-throw so the button can show an error state if needed
        }
    };

      const chatUser = user
    ? { name: user.name ?? "User", role: user.role as "STUDENT" | "TEACHER" | "ADMIN" }
    : null;

    return (
        

        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >

            <NavBar
                user={user}
                isLoadingUser={isLoadingUser}
                onSignOut={handleSignOut}
                onChangePassword={handleChangePassword}
                onVerifyEmail={handleVerifyEmail}
            />
    <ChatWidget user={chatUser} loginPath="/auth/signin" />
            {children}
            <FooterSection></FooterSection>

        </ThemeProvider>

    );
}
