"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { useCallback, useEffect, useState } from "react";
import { RiAlertLine, RiBarChartBoxLine, RiCheckLine, RiCloseLine, RiShieldCheckLine, RiTimeLine, RiUserLine } from "react-icons/ri";
import { toast } from "sonner";
import { examApi } from "@/lib/api";

export default function AdminExamsPage() {
  const [pending, setPending] = useState<any[]>([]); const [analytics, setAnalytics] = useState<any>({ exams: [], clusters: [], upcoming: [] }); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [p, a] = await Promise.all([examApi.pending(), examApi.analytics()]); setPending(p.data ?? []); setAnalytics(a.data ?? { exams: [], clusters: [], upcoming: [] }); } catch (e: any) { toast.error(e.message) ;} finally { setLoading(false) ;} }, []);
  useEffect(() => { load() ;}, [load]);
  const reject = async (id: string) => { const reason = window.prompt("Rejection reason"); if (!reason) return; await examApi.reject(id, reason); toast.success("Exam rejected"); load() ;};
  return <div className="flex flex-col gap-7 p-5 lg:p-8 max-w-6xl mx-auto w-full">
    <div><div className="text-[10px] tracking-[.14em] uppercase font-bold text-teal-600 flex items-center gap-2"><RiShieldCheckLine /> Admin · ExamShield</div><h1 className="text-2xl font-extrabold mt-1">Exam approvals & analytics</h1><p className="text-[13px] text-muted-foreground">Review question sets and monitor platform-wide exam integrity.</p></div>
    <section><h2 className="font-extrabold text-[14px] mb-3">Pending approval <span className="text-amber-600">({pending.length})</span></h2>{loading ? <div className="h-32 bg-muted rounded-2xl animate-pulse" /> : <div className="space-y-3">{pending.map(e => <div key={e.id} className="rounded-2xl border border-border bg-card p-5 flex gap-4 items-start"><div className="w-10 h-10 rounded-xl bg-amber-500/10 text-amber-600 flex items-center justify-center"><RiTimeLine /></div><div className="flex-1"><h3 className="font-extrabold text-[14px]">{e.title}</h3><p className="text-[12px] text-muted-foreground">{e.cluster?.name} · {e.type} · {e.questions.length} questions · {e._count.assignments} students</p><p className="text-[11px] mt-2 flex gap-1 items-center"><RiUserLine /> {e.teacher.user.name} · starts {new Date(e.startTime).toLocaleString()}</p></div><button onClick={async () => { await examApi.approve(e.id); toast.success("Exam approved"); load() ;}} className="h-9 px-4 bg-teal-600 text-white rounded-xl text-[12px] font-bold flex gap-1 items-center"><RiCheckLine />Approve</button><button onClick={() => reject(e.id)} className="h-9 px-4 border border-rose-300 text-rose-600 rounded-xl text-[12px] font-bold flex gap-1 items-center"><RiCloseLine />Reject</button></div>)}</div>}</section>
    <section><h2 className="font-extrabold text-[14px] mb-3">Upcoming approved exams</h2><div className="flex gap-3 overflow-x-auto pb-2">{analytics.upcoming.map((e: any) => <div key={e.id} className="min-w-64 rounded-2xl border border-teal-300/30 bg-teal-500/5 p-4"><p className="font-extrabold text-[13px]">{e.title}</p><p className="text-[11px] text-muted-foreground">{e.cluster?.name}</p><p className="text-[11px] text-teal-600 mt-2 flex gap-1 items-center"><RiTimeLine />{new Date(e.startTime).toLocaleString()}</p></div>)}</div></section>
    <section><h2 className="font-extrabold text-[14px] mb-3 flex gap-2 items-center"><RiBarChartBoxLine className="text-teal-600" /> Cluster analytics</h2><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{analytics.clusters.map((c: any) => <div key={c.id} className="rounded-2xl border border-border bg-card p-5"><h3 className="font-extrabold text-[14px]">{c.name}</h3><p className="text-[11px] text-muted-foreground">{c.exams} exams</p><div className="grid grid-cols-3 gap-2 mt-4 text-center"><div className="rounded-xl bg-teal-500/10 p-2"><b className="text-teal-600">{c.participationRate}%</b><p className="text-[9px]">participation</p></div><div className="rounded-xl bg-sky-500/10 p-2"><b className="text-sky-600">{c.averageScore}%</b><p className="text-[9px]">average</p></div><div className="rounded-xl bg-rose-500/10 p-2"><b className="text-rose-600">{c.violationCount}</b><p className="text-[9px]">violations</p></div></div></div>)}</div></section>
    <section><h2 className="font-extrabold text-[14px] mb-3 flex gap-2 items-center"><RiBarChartBoxLine className="text-teal-600" /> Exam performance</h2><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{analytics.exams.map((e: any) => <div key={e.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex justify-between"><h3 className="font-extrabold text-[14px]">{e.title}</h3><span className="text-[10px] font-bold text-muted-foreground">{e.status}</span></div><p className="text-[11px] text-muted-foreground mt-1">{e.cluster?.name}</p><div className="grid grid-cols-3 gap-2 mt-4 text-center"><div className="rounded-xl bg-teal-500/10 p-2"><b className="text-teal-600">{e.participationRate}%</b><p className="text-[9px]">participation</p></div><div className="rounded-xl bg-sky-500/10 p-2"><b className="text-sky-600">{e.averageScore}%</b><p className="text-[9px]">average</p></div><div className="rounded-xl bg-rose-500/10 p-2"><b className="text-rose-600">{e.violationCount}</b><p className="text-[9px]">violations</p></div></div>{e.violationCount > 0 && <p className="text-[11px] text-rose-600 mt-3 flex gap-1"><RiAlertLine />Integrity review recommended</p>}</div>)}</div></section>
  </div>;
}
