"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { useCallback, useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { RiAlertLine, RiCheckboxCircleLine, RiFullscreenLine, RiLoader4Line, RiShieldCheckLine, RiTimeLine } from "react-icons/ri";
import { toast } from "sonner";
import { examApi } from "@/lib/api";
import { cn } from "@/lib/utils";

export default function ExamRunnerPage() {
  const { examId } = useParams<{ examId: string; }>(); const router = useRouter();
  const [exam, setExam] = useState<any>(null); const [answers, setAnswers] = useState<Record<string, { optionId?: string; textAnswer?: string ;}>>({});
  const [started, setStarted] = useState(false); const [submitting, setSubmitting] = useState(false); const [seconds, setSeconds] = useState(0); const submitted = useRef(false);
  const log = useCallback((type: string, metadata?: any) => { if (!started || submitted.current) return; examApi.violation(examId, { type, pageUrl: location.href, referrer: document.referrer, metadata }).catch(() => { }) ;}, [examId, started]);
  const submit = useCallback(async (auto = false) => { if (submitted.current) return; submitted.current = true; setSubmitting(true); try { await examApi.submit(examId, Object.entries(answers).map(([questionId, a]) => ({ questionId, ...a })), auto); toast.success(auto ? "Time expired. Exam auto-submitted." : "Exam submitted"); router.push("/dashboard/student/exams") ;} catch (e: any) { submitted.current = false; toast.error(e.message) ;} finally { setSubmitting(false) ;} }, [answers, examId, router]);

  const begin = async () => { try { await document.documentElement.requestFullscreen(); const data = (await examApi.start(examId)).data; setExam(data); setStarted(true); const hardEnd = new Date(data.endTime).getTime(); const durationEnd = data.durationMinutes ? new Date(data.startedAt).getTime() + data.durationMinutes * 60000 : hardEnd; setSeconds(Math.max(0, Math.floor((Math.min(hardEnd, durationEnd) - Date.now()) / 1000))) ;} catch (e: any) { toast.error(e.message) ;} };
  useEffect(() => { if (!started) return; const timer = setInterval(() => setSeconds(s => { if (s <= 1) { clearInterval(timer); submit(true); return 0 ;} return s - 1 ;}), 1000); return () => clearInterval(timer) ;}, [started, submit]);
  useEffect(() => { if (!started) return; const visibility = () => document.hidden && log("TAB_HIDDEN"); const blur = () => log("WINDOW_BLUR"); const fullscreen = () => !document.fullscreenElement && log("FULLSCREEN_EXIT"); const copy = (e: Event) => { e.preventDefault(); log("COPY_ATTEMPT") ;}; const paste = (e: Event) => { e.preventDefault(); log("PASTE_ATTEMPT") ;}; const before = () => log("PAGE_EXIT", { reason: "refresh-or-close" }); document.addEventListener("visibilitychange", visibility); window.addEventListener("blur", blur); document.addEventListener("fullscreenchange", fullscreen); document.addEventListener("copy", copy); document.addEventListener("paste", paste); window.addEventListener("beforeunload", before); return () => { document.removeEventListener("visibilitychange", visibility); window.removeEventListener("blur", blur); document.removeEventListener("fullscreenchange", fullscreen); document.removeEventListener("copy", copy); document.removeEventListener("paste", paste); window.removeEventListener("beforeunload", before) ;} ;}, [started, log]);
  if (!started) return <div className="max-w-xl mx-auto p-5 lg:p-8"><div className="rounded-2xl border border-teal-300/40 bg-card p-8 text-center shadow-xl"><div className="w-16 h-16 rounded-2xl bg-teal-500/10 text-teal-600 flex items-center justify-center text-3xl mx-auto"><RiShieldCheckLine /></div><h1 className="text-xl font-extrabold mt-5">Secure exam environment</h1><p className="text-[13px] text-muted-foreground mt-2">Entering starts your attempt and fullscreen monitoring. Tab switches, page exits, fullscreen exits, copy, and paste attempts are recorded.</p><div className="mt-5 rounded-xl bg-amber-500/10 border border-amber-300/30 p-3 text-[12px] text-amber-700 flex gap-2 text-left"><RiAlertLine className="shrink-0 mt-0.5" />Close unrelated tabs and ensure a stable connection before starting.</div><button onClick={begin} className="mt-6 w-full h-11 rounded-xl bg-teal-600 text-white font-bold text-[13px] flex gap-2 items-center justify-center"><RiFullscreenLine />Enter fullscreen & start</button></div></div>;
  const clock = `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${(seconds % 60).toString().padStart(2, "0")}`;
  return <div className="min-h-screen bg-background select-none">
    <div className="sticky top-0 z-20 border-b border-border bg-card/95 backdrop-blur px-5 py-3 flex items-center gap-4"><div className="w-9 h-9 rounded-xl bg-teal-500/10 text-teal-600 flex items-center justify-center"><RiShieldCheckLine /></div><div className="flex-1"><h1 className="text-[14px] font-extrabold">{exam.title}</h1><p className="text-[10px] text-muted-foreground">Proctoring active</p></div><div className={cn("rounded-xl border px-4 py-2 font-mono font-bold flex gap-2 items-center", seconds < 300 ? "border-rose-300 text-rose-600 bg-rose-500/10" : "border-teal-300 text-teal-600 bg-teal-500/10")}><RiTimeLine />{clock}</div><button onClick={() => submit(false)} disabled={submitting} className="h-10 px-4 rounded-xl bg-teal-600 text-white text-[12px] font-bold flex gap-2 items-center">{submitting ? <RiLoader4Line className="animate-spin" /> : <RiCheckboxCircleLine />}Submit</button></div>
    <div className="max-w-3xl mx-auto p-5 lg:p-8 space-y-5">{exam.questions.map((q: any, i: number) => <section key={q.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex justify-between gap-3"><h2 className="font-extrabold text-[14px] leading-relaxed"><span className="text-teal-600 mr-2">{i + 1}.</span>{q.prompt}</h2><span className="text-[10px] font-bold text-muted-foreground shrink-0">{q.marks} marks</span></div>{q.type === "MCQ" ? <div className="mt-4 space-y-2">{q.options.map((o: any) => <label key={o.id} className={cn("flex gap-3 items-center p-3 rounded-xl border cursor-pointer transition-colors", answers[q.id]?.optionId === o.id ? "border-teal-400 bg-teal-500/10" : "border-border hover:bg-muted/30")}><input type="radio" name={q.id} checked={answers[q.id]?.optionId === o.id} onChange={() => setAnswers(p => ({ ...p, [q.id]: { optionId: o.id } }))} /><span className="text-[13px]">{o.text}</span></label>)}</div> : <textarea rows={8} className="mt-4 w-full rounded-xl border border-border bg-muted/20 p-3 text-[13px] focus:outline-none focus:ring-2 focus:ring-teal-400/20 resize-y" placeholder="Write your answer..." value={answers[q.id]?.textAnswer ?? ""} onChange={e => setAnswers(p => ({ ...p, [q.id]: { textAnswer: e.target.value } }))} />}</section>)}</div>
  </div>;
}
